[[cells]]
name = "poke_point"
enable_type_id = true
location = { file = "dist/index.bc" }
force_redeploy = true

# Dep group cells
[[dep_groups]]
name = "poke_point_dep_group"
cells = [
  "poke_point"
]

# The lock script set to output cells
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0xa95d7caffda25859a126b4c9adf2b178231b3bd4"
hash_type = "type"

